const dataClothes = [
    {
        id:1,
        title:'Buzo Bones',
        description:'Buzo de color negro con estampado de esqueleto estilo oversize ',
        price:'5000ARS',
        pictureUrl:'https://i.ibb.co/xg4y6zL/buzo-bones.png',
        category:'1',
        stock:'5'
    },
    {
        id:2,
        title:'buzo2',
        description:'ascasdasdasda',
        price:'asc',
        pictureUrl:'https://i.ibb.co/M6t1bYd/buzo-donnie.png',
        category:'1',
        stock:'10'
    },
    {
        id:3,
        title:'buzo3',
        description:'asasdasddddddddc',
        price:'asc',
        pictureUrl:'https://i.ibb.co/fdW9QnC/buzo-jack.png',
        category:'1',
        stock:'1'
    },
    {
        id:4,
        title:'buzo4',
        description:'ascdfgdfgg',
        price:'ascasdehtfghfgh',
        pictureUrl:'https://i.ibb.co/N72wHfq/buzo-la-mort.png',
        category:'1',
        stock:'7'
    },
    {
        id:5,
        title:'buzo5',
        description:'asdehtffghfghfghghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/5X3nh1c/buzo-world.png',
        category:'1',
        stock:'17'
    },
    {
        id:6,
        title:'buzo6',
        description:'asdehtfghfghjgfhfgfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/RbSfdzX/camiseta-joey.png',
        category:'3',
        stock:'0'
    },
    {
        id:7,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/jwznGhH/falda-brody-amarilla.png',
        category:'2',
        stock:'3'
    },
    {
        id:8,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/GxjwxgH/falda-brody-rayas.png',
        category:'2',
        stock:'18'
    },
    {
        id:9,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/MNNqt9B/falda-escocesa-negra.png',
        category:'2',
        stock:'13'
    },
    {
        id:10,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/0sg2Dd6/falda-escocesa-roja.png',
        category:'2',
        stock:'5'
    },
    {
        id:11,
        title:'remera',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/R3JcjbS/remera-kimono.png',
        category:'3',
        stock:'10'
    },
    {
        id:12,
        title:'remera',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://i.ibb.co/JRv8sfm/remera-stn.png',
        category:'3',
        stock:'1'
    },
    
];
export default dataClothes;