const dataClothes = [
    {
        id:1,
        title:'Buzo Bones',
        description:'Buzo de color negro con estampado de esqueleto estilo oversize ',
        price:'5000ARS',
        pictureUrl:'./img/buzo-bones.png',
        category:'1'
    },
    {
        id:2,
        title:'buzo2',
        description:'ascasdasdasda',
        price:'asc',
        pictureUrl:'../img/buzo-donnie.png',
        category:'1'
    },
    {
        id:3,
        title:'buzo3',
        description:'asasdasddddddddc',
        price:'asc',
        pictureUrl:'../img/buzo-jack.png',
        category:'1'
    },
    {
        id:4,
        title:'buzo4',
        description:'ascdfgdfgg',
        price:'ascasdehtfghfgh',
        pictureUrl:'../img/buzo-la-mort.png',
        category:'1'
    },
    {
        id:5,
        title:'buzo5',
        description:'asdehtffghfghfghghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/buzo-world.png',
        category:'1'
    },
    {
        id:6,
        title:'buzo6',
        description:'asdehtfghfghjgfhfgfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/camiseta-joey.png',
        category:'3'
    },
    {
        id:7,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/falda-brody-amarilla.png',
        category:'2'
    },
    {
        id:8,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/falda-brody-rayas.png',
        category:'2'
    },
    {
        id:9,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/falda-escocesa-bw.png',
        category:'2'
    },
    {
        id:10,
        title:'falda',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/falda-escocesa-roja.png',
        category:'2'
    },
    {
        id:11,
        title:'remera',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/remera-kimono.png',
        category:'3'
    },
    {
        id:12,
        title:'remera',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'../img/remera-stn.png',
        category:'3'
    },
    
];
export default dataClothes;