const dataClothes = [
    {
        id:'1',
        title:'Buzo Bones',
        description:'Buzo de color negro con estampado de esqueleto estilo oversize ',
        price:'5000ARS',
        pictureUrl:'https://ibb.co/myxm4hT'
    },
    {
        id:'2',
        title:'asc',
        description:'asc',
        price:'asc',
        pictureUrl:'https://ibb.co/6s2q8xX'
    },
    {
        id:'3',
        title:'asc',
        description:'asc',
        price:'asc',
        pictureUrl:'https://ibb.co/7vfsmGx'
    },
    {
        id:'4',
        title:'asc',
        description:'asc',
        price:'ascasdehtfghfgh',
        pictureUrl:'https://ibb.co/TwTcjTb'
    },
    {
        id:'5',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/y4wM2ky'
    },
    {
        id:'6',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/1n1HKhZ'
    },
    {
        id:'7',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/Ytjgf67'
    },
    {
        id:'8',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/6PMM2Tn'
    },
    {
        id:'9',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/VqzrHgG'
    },
    {
        id:'10',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/RS15Dnn'
    },
    {
        id:'11',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/3Nstzf5'
    },
    {
        id:'12',
        title:'asdehtfghfgh',
        description:'asdehtfghfgh',
        price:'asdehtfghfgh',
        pictureUrl:'https://ibb.co/qRV5f5d'
    },
    
];
export default dataClothes;